kind: ImageStream
apiVersion: v1
metadata:
  name: hugo
  creationTimestamp: null
spec:
  tags:
  - name: latest
    annotations:
      description: Hugo static site generator
      openshift.io/display-name: Hugo v0.19
      sampleRepo: https://github.com/thedigitalgarage/hugo-ex.git
      iconClass: icon-go
      supports: hugo:019,hugo
      tags: builder,hugo,jamstack,go
      version: "0.19"
    from:
      kind: ImageStreamTag
      name: "0.19"
  - name: "0.19"
    from:
      kind: DockerImage
      name: thedigitalgarage/sti-hugo019-alpine:latest
